import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Analytics from "@/components/analytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark bg-green-900 h-screen w-full flex`}
      >
        <Analytics measurementId={process.env.GOOGLE_MEASUREMENT_ID!} />
        {children}
      </body>
    </html>
  );
}
